deployment:
  name: dummy-app
  replicas: 1

image:
  repository: hashicorp/http-echo 
  tag: "latest"                    
  args: ["-text='Hello world'"]

service:
  name: dummy-service
  type: ClusterIP
  port: 5678