apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EriccKP/k3s-je-homework.git
    path: HelmCharts/ChartTest1
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values_dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true